### ISSUE TITLE
MessageIDs are shown too large

### ISSUE THREAD

**Issue by lukechurch** [AfricasVoices/CodaV2#126]
<img width="1328" alt="screen shot 2018-10-29 at 08 11 05" src="https://user-images.githubusercontent.com/2978182/47637085-73b76480-db52-11e8-9923-c4f22eb8ab22.png">

**Comment by lukechurch** [comment]
Did we fix this already? @marianamarasoiu

**Comment by marianamarasoiu** [comment]
This should be fixed by PR #136 where the ID in the UI is replaced with a sequence number
