### ISSUE TITLE
Decrease console chatter

### ISSUE THREAD

**Issue by marianamarasoiu** [AfricasVoices/CodaV2#65]
We shouldn't be writing something to the console for every message

**Comment by marianamarasoiu** [comment]
@lukechurch 

Currently, everytime a message is being coded in the UI, we generate the following logs:

```
2018-10-17T18:48:28.605: Message code-value: msg---1010 Scheme-a53e400f => value-2787929c
dart_sdk.js:18257 2018-10-17T18:48:28.605: Updating: msg---1010: Text text text [Scheme-a53e400f: value-2787929c Manual info@example.com]
dart_sdk.js:18257 2018-10-17T18:48:28.683: setupListenerForFirebaseMessageUpdates: Skipping processing of local messages
dart_sdk.js:18257 2018-10-17T18:48:28.918: Store complete: msg---1010
```

How much of this do you think we should we try to eliminate?

**Comment by lukechurch** [comment]
I'm ok with us writing quite a lot to the log in response to a user action. I'm only really concerned about content written to the log in response to system actions
